# docker-compose.yml (CORRIGIDO)
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app/app
      - ./frontend:/app/frontend:ro
      - ./generated_audio:/app/generated_audio
    environment:
      - DATABASE_URL=sqlite:///./suno.db
      - OUTPUT_DIR=/app/generated_audio
    ports:
      - "8000:8000"
    depends_on:
      - suno-api

  # O serviço 'suno-api' foi movido para o nível correto
  suno-api:
    # Usando a imagem pública recomendada em vez de um build local
    image: ghcr.io/gcui-art/suno-api:v1.2.3-full
    env_file:
      - .env
    environment:
      - BROWSER=chromium
      - BROWSER_GHOST_CURSOR=false
      - BROWSER_LOCALE=en
      - BROWSER_HEADLESS=true
    ports:
      - "3000:3000"
    volumes:
      - ./suno-api/public:/app/public

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: suno
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  # O volume suno_api_public não é mais necessário com a imagem pública