# docker-compose.yml - Nova API Suno (SunoAI-API)
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app/app
      - ./frontend:/app/frontend:ro
      - ./generated_audio:/app/generated_audio
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/suno
      - OUTPUT_DIR=/app/generated_audio
      - SUNO_API_URL=http://suno-api:3000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - suno-api
    restart: unless-stopped

  suno-api:
    build:
      context: ./suno-api
    env_file:
      - ./suno-api/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: suno
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: