# docker-compose.yml (CORRIGIDO PARA BUILD LOCAL)
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app/app
      - ./frontend:/app/frontend:ro
      - ./generated_audio:/app/generated_audio
    environment:
      - DATABASE_URL=sqlite:///./suno.db
      - OUTPUT_DIR=/app/generated_audio
    ports:
      - "8000:8000"
    depends_on:
      - suno-api

  # Esta seção agora constrói a imagem a partir da pasta 'suno-api' local.
  suno-api:
    build: ./suno-api
    env_file:
      - .env
    environment:
      - BROWSER=chromium
      - BROWSER_GHOST_CURSOR=false
      - BROWSER_LOCALE=en
      - BROWSER_HEADLESS=true
    ports:
      - "3000:3000"
    volumes:
      - ./suno-api/public:/app/public

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: suno
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: